### PR TITLE
Add support for Active Record 5 to Gemfile

### PR DESCRIPTION
**Pull request by vinhhv**
Changed Gemfile to use new version of Active Record (version 5.0.0)

### CODE REVIEW

**Comment by thuss** [comment]
Looks like the travis CI tests are failing because Rails 5 requires ruby 2.2.2 or later. So you'll need to update .travis.yml to specify rvm 2.2.2.

**Comment by vinhhv** [comment]
Okay, thanks for the tip. Should I have removed the other versions, 1.9.3 and 2.2.0, as well?

**Comment by twobitlabs** [comment]
yeah, I think the travis builds are still failing because it's running the tests on all 3 ruby versions listed in the travis file.

**Comment by twobitlabs** [comment]
Thanks for the PR!

**Pull request merged**
