### PR TITLE
Use File.exist? instead of deprecated/removed File.exists?

### PR DESCRIPTION
**Pull request by piotaixr**
Fix is available on master branch of https://github.com/piotaixr/standalone-migrations

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
As a workaround if this is not fixed:
```
class File
  class << self
    alias_method :exists?, :exist?
  end
end
```

**Comment by hamza-yusuff** [comment]
> Fix is available on master branch of https://github.com/piotaixr/standalone-migrations

@piotaixr  @AlfonsoUceda any chance this could be merged to main soon?

**Comment by owst** [comment]
Ping @thuss - could you take a look and merge this PR please? `File.exists?` was removed in Ruby 3.2: https://github.com/ruby/ruby/pull/5352

**Comment by thuss** [comment]
Thanks for the fix @piotaixr and the ping @owst! Published new gem version 7.1.1 with this change.

**Pull request merged**
