### PR TITLE
Add support for rails 6.0.0

### PR DESCRIPTION
**Pull request by marcoadkins**
## Things Done:
- Updated gemfile to support rails 6.
- Ran a bundle update to update all gems.
- Added additional configuration to the travis yml to test rails version 6.
  - Bumped ruby version to 2.5.7
  - Added ruby version to 2.6.5 to travis build matrix
  - Accept sqllite3 gem version from env to allow diff versions to be tested. 

Resolves: #157

### CODE REVIEW

**Comment by samstickland** [comment]
Is there any chance of this being reviewed and merged?

**Comment by wtn** [comment]
Please target activerecord `~> 6.0.0` and not specifically `6.0.0`.

Also, requiring railties seems excessive; that requires actionpack and actionview which are not needed.

**Comment by pzula** [comment]
What's the chance of this being merged?

**Comment by anklos** [comment]
hope this could get merged soon

**Comment by lchojnowski** [comment]
+1 hello, I can merge it :)

**Comment by anklos** [comment]
@lchojnowski any chance to bump activerecord version a bit to to support `6.0.3.1`

**Comment by marcoadkins** [comment]
@anklos @wtn I think I resolved both of your requests. Let me know if anyone finds any issue while testing it out. Otherwise this is ready to merge. I went ahead and added ruby 2.6.5 to the travis build matrix as well.

**Comment by thuss** [comment]
Thanks for this excellent contribution, I'll try and get it reviewed and merged in the next day or two.

**Comment by thuss** [comment]
Published version 6 of the gem, thanks again for the contribution: https://rubygems.org/gems/standalone_migrations/versions/6.0.0

**Pull request merged**
