### PR TITLE
Support Rails 7.1

### PR DESCRIPTION
**Pull request by owst**
`db:test:load` was removed in https://github.com/rails/rails/pull/45870

### CODE REVIEW

**Comment by owst** [comment]
@thuss please could you approve the workflow to see if the CI tests pass? The tests pass locally with 6.1.6, 7.0.6 and 7.1.1 so I'm hopeful they will!

**Comment by thuss** [comment]
Thanks for the PR!!

**Comment by thuss** [comment]
If you'd like credit for the 7 support, feel free to update the Readme announcing 7 support and add your name to the list of maintainers!

**Comment by owst** [comment]
Thanks for merging @thuss - I'll leave it to you to announce 7.1 support - it wasn't much effort from me and I'm not looking to take on maintainership, but thanks for the offer

**Pull request merged**
