### PR TITLE
Allowing Rails 5.1

### PR DESCRIPTION
**Pull request by jrochkind**
No changes to actual functional code was required to get this to pass existing tests with Rails 5.1.0.rc2, just changes to test infrastructure:

* Removed Gemfile.lock from repo. This is considered best practice for gems, and allows us to have travis test under multiple Rails versions, which I've done -- travis will now be testing under latest 4.2, 5.0, and 5.1. 

* Rails 5.1 _requires_ migrations to be like `< ActiveRecord::Migration[5.0]`. The spec files were generating a migration without that; fixed to do it like that in 5.0 (where it's allowed), and 5.1 (where it's required), but not 4.2 (where not supported). 

* Workaround a bug in Rails where it is raising the wrong exception from `db:migrations:down` (or up) without a `VERSION`, causing the spec to false positive. 

* And of course change the gemspec to allow Rails 5.1.

### CODE REVIEW

**Comment by twobitlabs** [comment]
PR looks good, once it's passing in travis I'll merge it, thanks!

Also don't forget to add your name to the README as a contributor if you'd like.

**Comment by twobitlabs** [comment]
Thanks for the excellent PR @jrochkind

**Comment by twobitlabs** [comment]
Published version 5.2.0: https://rubygems.org/gems/standalone_migrations

**Comment by jrochkind** [comment]
@twobitlabs If you were trying to track rails versions, that should have been 5.1.0.  Rails 5.1.0.rc2 is out. Rails 5.2.0 is but a glimmer in someone's eye. Looks like you now have a released `standalone_migrations` 5.0.0, and 5.2.0, but no 5.1.0. https://rubygems.org/gems/standalone_migrations

Not sure what you're trying to do with version numbers, or how you can recover from this -- rubygems will never let you release anything else called 5.2.0 but this in the future at this point.

**Comment by jrochkind** [comment]
Also, this version just released supports Rails 4.2.x, 5.0.x, and 5.1.x, it supports all of them just fine (at least the tests pass on all of them) -- I'm not sure why you're trying to track Rails versions, if that's what you were doing.

**Comment by twobitlabs** [comment]
Yeah, that was an accident. I looked at the Gemfile and saw 5.2.0 but didn't read it carefully enough. Not a big deal though... when 5.2 comes out I'll just bump the patch number instead of the minor number.

**Comment by jrochkind** [comment]
Woah, and just in time for Rails 5.1.0!  The final (non-rc) release was literally released in between the time I made the PR and now. :)

**Pull request merged**
